version: 2.1

references:
  on_checkout: &on_checkout
    checkout:
      path: nav2_docs
  setup_doc_dependencies: &setup_doc_dependencies
    run:
      name: Install Doc Dependencies
      command: |
        export DEBIAN_FRONTEND=noninteractive
        apt update
        apt install make -y
        apt install doxygen -y
        apt install graphviz -y
        apt install ttf-dejavu -y
        apt install openjdk-8-jre -y
        apt install bash git openssh-server -y
        pip3 install sphinx==1.7.5 docutils==0.14 sphinx_rtd_theme breathe==4.9.1 sphinxcontrib-plantuml
  make_docs: &make_docs
    run:
      command: |
        cd nav2_docs
        make html
  store_docs: &store_docs
    store_artifacts:
        path: nav2_docs/_build/html
        destination: html
  publish_docs: &publish_docs
    run:
      command: |
        cd nav2_docs
        make publish
  install_deployment_key: &install_deployment_key
    add_ssh_keys:
      fingerprints:
        - "f1:50:e5:1b:95:e6:38:aa:f8:71:f3:f8:ba:35:f5:46"

commands:
  install_doc_dependencies:
    description: "Install documentation dependencies"
    steps:
      - *setup_doc_dependencies
  build_docs:
    description: "Build docs"
    steps:
      - *make_docs
      - *store_docs
  publish_docs_to_gh_pages_branch:
    description: "Commit newly built docs to gh-pages branch"
    steps:
      - *publish_docs

executors:
  docs_exec:
    docker:
      - image: ubuntu:focal
    working_directory: /

jobs:
  docs_build:
    executor: docs_exec
    steps:
      - install_doc_dependencies
      - *on_checkout
      - build_docs
      - persist_to_workspace:
          root: nav2_docs
          paths:
            - _build 
  docs_publish:
    executor: docs_exec
    steps:
      - install_doc_dependencies
      - *on_checkout
      - *install_deployment_key
      - attach_workspace:
          at: nav2_docs
      - publish_docs_to_gh_pages_branch

workflows:
  version: 2
  build_and_publish_docs:
    jobs:
      - docs_build
      - docs_publish:
          requires:
            - docs_build
          filters:
            branches:
              only: master
